Web_Server:
  image: letsjump/pineta-v2
  # restart: always
  container_name: DKP_Web_Server
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./application:/var/www
    - ./docker-data/web-server/etc/apache2/sites-available:/etc/apache2/sites-available
    - /etc/localtime:/etc/localtime
    - ./docker-data/shared-folder:/root/backup
  environment:
    - GITHUB_API_TOCKEN=<put your key key here>
  links:
    - Database_Server:dbserver
  ports:
    - 80:80

Database_Server:
  container_name: DKP_Database_Server
  image: mysql:5.5
  # restart: always
  volumes:
    - /etc/localtime:/etc/localtime
    - ./docker-data/db-server/etc/mysql:/etc/mysql
    - ./docker-data/db-server/var/lib/mysql:/var/lib/mysql
    - ./docker-data/shared-folder:/root/backup
  environment:
    - MYSQL_ROOT_PASSWORD=root 
    - MYSQL_DATABASE=<database name here>
    - MYSQL_USER=<user here>
    - MYSQL_PASSWORD=<password here>
    - TZ=UTC
  ports:
    - 3306:3306
    
Redis_Server:
    container_name: DKP_Redis_Server
    image: redis:alpine
    ports:
    - "6379"
    volumes:
    - /etc/localtime:/etc/localtime
